import json
import pathlib
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[1]


class ChartLingoV2Tests(unittest.TestCase):
    def test_v2_is_self_contained(self):
        for name in ["index.html", "styles.css", "core.js", "app.js", "README.md"]:
            self.assertTrue((ROOT / name).is_file(), name)

    def test_workspace_placeholders_replace_intro_page(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        self.assertNotIn('id="emptyState"', index)
        self.assertIn('<section id="app">', index)
        self.assertIn('class="panel-placeholder"', index)
        self.assertIn('No package loaded', index)
        self.assertNotIn("$('emptyState')", app)

    def test_schema_contracts_are_versioned(self):
        package = json.loads((ROOT / "schemas/package-v2.schema.json").read_text())
        result = json.loads((ROOT / "schemas/result-v2.schema.json").read_text())
        self.assertEqual(package["$id"], "https://chartlingo.local/schemas/package-v2.json")
        self.assertEqual(result["$id"], "https://chartlingo.local/schemas/result-v2.json")
        self.assertEqual(package["properties"]["schemaVersion"]["const"], "2.0.0")
        self.assertEqual(result["properties"]["schemaVersion"]["const"], "2.0.0")

    def test_multiline_text_is_one_source_object(self):
        core = (ROOT / "core.js").read_text()
        self.assertIn("visibleLines:['航程缩短3小时，','新加坡经济可获什么？']", core)
        self.assertIn("sourceText:'航程缩短3小时，新加坡经济可获什么？'", core)
        self.assertEqual(core.count("id:'headline-01'"), 1)

    def test_axis_and_credit_fields_are_atomic_data_records(self):
        core = (ROOT / "core.js").read_text()
        app = (ROOT / "app.js").read_text()
        package_schema = (ROOT / "schemas/package-v2.schema.json").read_text()
        result_schema = (ROOT / "schemas/result-v2.schema.json").read_text()
        self.assertIn("CLV2.atomicTextFrames", core)
        self.assertIn("sourceText:lines[0]", core)
        self.assertIn("sourceText:lines[1]", core)
        self.assertIn("board.textFrames=CLV2.atomicTextFrames", core)
        self.assertIn("data-group-id", app)
        self.assertIn("data-field-type", app)
        self.assertIn("groupId:o.originalSource.groupId", app)
        self.assertIn('"groupId"', package_schema)
        self.assertIn('"fieldType"', package_schema)
        self.assertIn('"pairId"', result_schema)

    def test_direct_and_illustrator_exports_exist(self):
        app = (ROOT / "app.js").read_text()
        self.assertIn("function exportSvg()", app)
        self.assertIn("function exportPng()", app)
        self.assertIn("function exportResult()", app)
        self.assertTrue((ROOT / "illustrator/export-to-chartlingo.jsx").is_file())
        self.assertTrue((ROOT / "illustrator/apply-chartlingo-result.jsx").is_file())

    def test_embedded_svg_is_sanitized(self):
        core = (ROOT / "core.js").read_text()
        self.assertIn("CLV2.sanitizeSvg", core)
        self.assertIn("script,foreignObject,iframe,object,embed,audio,video", core)
        self.assertIn("name.startsWith('on')", core)

    def test_illustrator_scripts_do_not_require_native_json(self):
        exporter = (ROOT / "illustrator/export-to-chartlingo.jsx").read_text()
        importer = (ROOT / "illustrator/apply-chartlingo-result.jsx").read_text()
        self.assertIn("function jsonStringify", exporter)
        self.assertIn("function jsonParse", importer)
        self.assertNotIn("JSON.stringify", exporter)
        self.assertNotIn("JSON.parse", importer)

    def test_v2_removes_source_text_and_uses_1200px_output(self):
        core = (ROOT / "core.js").read_text()
        app = (ROOT / "app.js").read_text()
        self.assertIn("CLV2.removeSourceText", core)
        self.assertIn("querySelectorAll('text,textPath,flowRoot,flowPara')", core)
        self.assertIn("const width=1200", app)
        self.assertIn("sourceWidth=Number(artboard.bounds.width)", app)
        self.assertIn("naturalHeight=Math.round(sourceHeight*scaleY)", app)
        self.assertIn('transform="translate(0 ${-spec.cropTop}) scale(${spec.scale})"', app)
        self.assertNotIn("source-masks", app)
        self.assertNotIn("source-mask", app)

    def test_unmatched_text_is_retained_and_roboto_is_bundled(self):
        core = (ROOT / "core.js").read_text()
        app = (ROOT / "app.js").read_text()
        self.assertIn("pair?.en||frame.sourceText", core)
        self.assertIn("sourceRetained:!pair", core)
        self.assertIn("function updateMapping", app)
        self.assertIn("Use original Chinese content", app)
        self.assertIn("manual-match", app)
        self.assertIn("if(score<.82)pair=null", core)
        self.assertIn("'Roboto-Bold':'Roboto-Regular'", app)
        self.assertTrue((ROOT / "fonts/Roboto-Regular.ttf").is_file())
        self.assertTrue((ROOT / "fonts/Roboto-Bold.ttf").is_file())
        self.assertTrue((ROOT / "fonts/OFL.txt").is_file())

    def test_generated_text_can_be_dragged_and_exported_at_new_position(self):
        app = (ROOT / "app.js").read_text()
        styles = (ROOT / "styles.css").read_text()
        self.assertIn("function bindCanvasDragging", app)
        self.assertIn("node.onpointerdown", app)
        self.assertIn("item.layout.x=base.x+dx", app)
        self.assertIn("item.layout.y=base.y+dy", app)
        self.assertIn("cursor:grab", styles)

    def test_reference_title_style_and_source_locked_geometry(self):
        core = (ROOT / "core.js").read_text()
        app = (ROOT / "app.js").read_text()
        exporter = (ROOT / "illustrator/export-to-chartlingo.jsx").read_text()
        self.assertIn("CLV2.originalLayout", core)
        self.assertIn("sourceLocked:true", core)
        self.assertIn("function referenceTitleFrame", app)
        self.assertIn("x:147.73046875*scale", app)
        self.assertIn("y:106.2744140625*scale", app)
        self.assertIn("fontSize=65*scale", app)
        self.assertIn("fontWeight:700", app)
        self.assertIn("object.numericLocked||object.sourceRetained||object.source.referenceMatched", app)
        self.assertIn("fontFamily=o.source.style.fontFamily||'Roboto'", app)
        self.assertIn("fontPostScriptName:postScript", app)
        self.assertIn("candidate.bounds.y > artboards[i].bounds.height * 0.25", exporter)
        self.assertIn("titleCandidate.style.fontWeight = 700", exporter)

    def test_per_chart_reference_package_drives_translated_geometry(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        self.assertNotIn('id="referenceInput"', index)
        self.assertNotIn('id="loadSample"', index)
        self.assertIn("referencePkg:null", app)
        self.assertIn("function referenceFrame", app)
        self.assertIn("referenceKey(item.sourceText)===referenceKey(english)", app)
        self.assertIn("referenceMatched:true", app)
        self.assertIn("object.source.referenceMatched", app)
        self.assertIn("independent translation widths and structured metric groups", app)

    def test_reference_credits_have_an_eight_pixel_floor_and_wrap(self):
        app = (ROOT / "app.js").read_text()
        self.assertIn("function isCredit", app)
        self.assertIn("function isGraphicCredit", app)
        self.assertIn("zaobao\\s+(?:graphic|chart)", app)
        self.assertIn("fontSize=credit?28:", app)
        self.assertIn("x:60,width:spec.width-120", app)
        self.assertIn("height:48", app)
        self.assertIn("visibleLines=credit?[english]", app)

    def test_output_height_auto_fits_content(self):
        app = (ROOT / "app.js").read_text()
        self.assertIn("const width=1200", app)
        self.assertIn("cropWindows:new Map()", app)
        self.assertIn("function fitCropWindow", app)
        self.assertIn("contentTop-ARTBOARD_PADDING", app)
        self.assertIn("contentBottom+ARTBOARD_PADDING", app)
        self.assertIn("expandOnly&&previous", app)
        self.assertIn("cropBottom-cropTop", app)
        self.assertIn('id="english-layer" transform="translate(0 ${-spec.cropTop})"', app)
        self.assertIn("y:o.layout.y-spec.cropTop", app)

    def test_plain_list_labels_share_a_font_size(self):
        app = (ROOT / "app.js").read_text()
        self.assertIn("function normalizeListTypography", app)
        self.assertIn("let fontSize=26", app)
        self.assertIn("while(fontSize>18", app)
        self.assertIn("fontSize,1", app)
        self.assertIn("fontSize,2", app)
        self.assertIn("normalizeListTypography(list)", app)

    def test_headline_moves_instead_of_disconnecting_chart_content(self):
        app = (ROOT / "app.js").read_text()
        self.assertIn("contentShifts:new Map()", app)
        self.assertIn("function enforceHeaderGap", app)
        self.assertIn("contentTop-HEADER_CONTENT_GAP-title.layout.height", app)
        self.assertIn("enforceHeaderGap(artboard,list)", app)
        self.assertNotIn('stroke="#b8b8b8"', app)
        self.assertIn('transform="translate(0 ${-spec.cropTop}) scale(${spec.scale})"', app)
        self.assertNotIn("item.layout.y+shift", app)
        self.assertNotIn("titleLimit=", app)
        self.assertNotIn("visibleTop=spec.cropTop", app)
        self.assertIn("item.layout.y=base.y+dy", app)
        self.assertIn("Text position updated.", app)

    def test_header_and_credits_use_uploaded_reference_spec(self):
        app = (ROOT / "app.js").read_text()
        self.assertIn("147.73046875*scale", app)
        self.assertIn("106.2744140625*scale", app)
        self.assertIn("fontSize=65*scale", app)
        self.assertIn("function referenceCreditFrame", app)
        self.assertIn("43.66015625*scale", app)
        self.assertIn("y:frame.bounds.y", app)
        self.assertIn("fontSize:28*scale", app)
        self.assertIn("visibleLines:[english]", app)

    def test_untranslated_numbers_use_proportional_source_geometry(self):
        app = (ROOT / "app.js").read_text()
        self.assertIn("function isNumericContent", app)
        self.assertIn("function mappedBounds", app)
        self.assertIn("sourceWidth=Number(artboard.bounds.width)", app)
        self.assertIn("scaleX=width/sourceWidth", app)
        self.assertIn("numericLocked=mapping.sourceRetained&&isNumericContent", app)
        self.assertIn("method:numericLocked?'source coordinates'", app)
        self.assertNotIn("method:numericReference?'reference cell'", app)

    def test_strict_positions_and_text_free_illustrator_preview(self):
        core = (ROOT / "core.js").read_text()
        app = (ROOT / "app.js").read_text()
        exporter = (ROOT / "illustrator/export-to-chartlingo.jsx").read_text()
        self.assertIn("x=frame.bounds.x,y=frame.bounds.y", core)
        self.assertIn("sourceRetained&&original.visibleLines?.length>1", app)
        self.assertIn("readArtworkWithoutLiveText", exporter)
        self.assertIn("doc.textFrames[frameIndex].hidden = true", exporter)
        self.assertIn("doc.textFrames[frameIndex].opacity = 0", exporter)
        self.assertIn("version: '0.6.1'", exporter)

    def test_illustrator_exporter_supports_independent_multi_artboards(self):
        exporter = (ROOT / "illustrator/export-to-chartlingo.jsx").read_text()
        self.assertIn("function chooseArtboards", exporter)
        self.assertIn("Selected artboard", exporter)
        self.assertIn("All artboards in one package", exporter)
        self.assertIn("Specific range in one package", exporter)
        self.assertIn("Each artboard as a separate package", exporter)
        self.assertIn("function artboardFor(bounds)", exporter)
        self.assertIn("area > bestArea", exporter)
        self.assertIn("if (boardIndex < 0", exporter)
        self.assertIn("options.artboardRange = String(artboardIndex + 1)", exporter)
        self.assertIn("previewSvg: null, artworkSvg: null", exporter)
        self.assertIn("artboards[i].previewSvg = readSvg(artboards[i].index)", exporter)
        self.assertIn("position: {x: rect[0], y: rect[1]}", exporter)
        self.assertIn("orientation: width >= height ? 'landscape' : 'portrait'", exporter)
        self.assertIn("new Window('palette', 'ChartLingoV2 Export')", exporter)
        self.assertIn("Cancel export", exporter)
        self.assertIn("function progress(stage, current, total, artboardName)", exporter)
        self.assertIn("Preflight:", exporter)
        self.assertIn("Large/complex document detected", exporter)
        self.assertIn("readArtworkWithoutLiveText(artboardIndex, artboardRecord)", exporter)
        self.assertIn("states.push({index: frameIndex", exporter)
        self.assertIn("__CHARTLINGO_CANCELLED__", exporter)

    def test_logo_safe_credit_layout_is_exported_and_dynamic(self):
        app = (ROOT / "app.js").read_text()
        exporter = (ROOT / "illustrator/export-to-chartlingo.jsx").read_text()
        schema = (ROOT / "schemas/package-v2.schema.json").read_text()
        self.assertIn("function logoBoundsForArtboard", exporter)
        self.assertIn("logoBounds: logoBoundsForArtboard(i)", exporter)
        self.assertIn('"logoBounds"', schema)
        self.assertIn("function scaledLogoBounds", app)
        self.assertIn("function layoutBottomCredits", app)
        self.assertIn("logo.x-logoMargin", app)
        self.assertIn("CLV2.wrap(item.english,width,preferred,8)", app)
        self.assertIn("previousBottom+8", app)

    def test_chart_content_line_break_modes_are_scoped_and_exported(self):
        core = (ROOT / "core.js").read_text()
        app = (ROOT / "app.js").read_text()
        exporter = (ROOT / "illustrator/export-to-chartlingo.jsx").read_text()
        package_schema = (ROOT / "schemas/package-v2.schema.json").read_text()
        result_schema = (ROOT / "schemas/result-v2.schema.json").read_text()
        styles = (ROOT / "styles.css").read_text()
        self.assertIn("function isChartContent", app)
        self.assertIn("function updateLineBreakMode", app)
        self.assertIn('<option value="auto"', app)
        self.assertIn('<option value="single-line"', app)
        self.assertIn("Manual line breaks", app)
        self.assertIn("Match source layout", app)
        self.assertIn("function updateTranslationWidth", app)
        self.assertIn("translation-width", styles)
        self.assertIn("function independentWidth", app)
        self.assertIn("inheritSourceWidth", app)
        self.assertIn('"match-source"', package_schema)
        self.assertIn('"translationLayout"', result_schema)
        self.assertIn("CLV2.fixedLinesLayout", core)
        self.assertIn("frame.bounds.width", core)
        self.assertIn("contentFrame.contentType = 'chart'", exporter)
        self.assertIn("contentFrame.lineBreakMode = 'auto'", exporter)
        self.assertIn("contentFrame.translationLayout", exporter)
        self.assertIn('"lineBreakMode"', package_schema)
        self.assertIn('"manualLines"', result_schema)
        self.assertIn("line-break-control", styles)
        self.assertIn("contentType:o.originalSource.contentType||(isChartContent(o.originalSource)?'chart':null)", app)

    def test_chart_content_can_merge_and_regenerate_from_csv(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        importer = (ROOT / "illustrator/apply-chartlingo-result.jsx").read_text()
        schema = (ROOT / "schemas/result-v2.schema.json").read_text()
        styles = (ROOT / "styles.css").read_text()
        self.assertIn('id="mergeSelected"', index)
        self.assertIn('id="mergeCsvField"', index)
        self.assertIn("function mergeSelectedFromCsv", app)
        self.assertIn("mergedFrom=ordered.flatMap", app)
        self.assertIn("csvField:pair.ch", app)
        self.assertIn("method:'merged CSV field'", app)
        self.assertIn("function automaticStyleReference", app)
        self.assertIn("function structuralStyleRole", app)
        self.assertIn("function selectedStyleRole", app)
        self.assertIn("function styleSignature", app)
        self.assertIn("sameRow*100000+dominance*1000", app)
        self.assertIn("styleSource=manualStyle||automaticStyleReference", app)
        self.assertIn("baseSize=frame.style.fontSize||14", app)
        self.assertIn("style:{...styleSource.source.style}", app)
        self.assertNotIn("fontSize=median(stylePool.map", app)
        self.assertIn("styleReferenceId:styleSource.frameId", app)
        self.assertIn("styleRole,metricGroupId,slot,inheritStyle:true", app)
        self.assertIn("inheritStyle:true", app)
        self.assertIn("MERGED_MAX_SHRINK=.9", app)
        self.assertIn("sameColumnBelow=objects().filter", app)
        self.assertIn("item.layout.x<right&&item.layout.x+item.layout.width>left", app)
        self.assertIn("function mergedAutoLayout", app)
        self.assertIn("!o.mergedInto", app)
        self.assertIn("change.mergedFrom && change.mergedFrom.length", importer)
        self.assertIn("change.layout.lines.join('\\r')", importer)
        self.assertIn('"mergedFrom"', schema)
        self.assertIn('"csvField"', schema)
        self.assertIn('"styleReferenceId"', schema)
        self.assertIn('"styleRole"', schema)
        self.assertIn('"inheritStyle"', schema)
        self.assertIn("mapping-row.merged", styles)

    def test_infographic_text_and_indicators_export_independently(self):
        exporter = (ROOT / "illustrator/export-to-chartlingo.jsx").read_text()
        app = (ROOT / "app.js").read_text()
        package_schema = (ROOT / "schemas/package-v2.schema.json").read_text()
        result_schema = (ROOT / "schemas/result-v2.schema.json").read_text()
        self.assertIn("function graphicTextType", exporter)
        self.assertIn("'graphic-value'", exporter)
        self.assertIn("'graphic-percentage'", exporter)
        self.assertIn("graphicElements: []", exporter)
        self.assertIn("contentType: graphicDirection", exporter)
        self.assertIn("preserveOriginalColor: true", exporter)
        self.assertIn("sourceColor: fill", exporter)
        self.assertIn("Independent vector elements", exporter)
        self.assertIn("graphicElements:(artboard.graphicElements||[])", app)
        self.assertIn('"graphic-label"', package_schema)
        self.assertIn('"graphic-value"', package_schema)
        self.assertIn('"graphic-percentage"', package_schema)
        self.assertIn('"graphicElement"', package_schema)
        self.assertIn('"graphicElement"', result_schema)

    def test_infographic_metric_groups_use_non_overlapping_slots(self):
        exporter = (ROOT / "illustrator/export-to-chartlingo.jsx").read_text()
        app = (ROOT / "app.js").read_text()
        package_schema = (ROOT / "schemas/package-v2.schema.json").read_text()
        result_schema = (ROOT / "schemas/result-v2.schema.json").read_text()
        self.assertIn("function sourceGroupKey", exporter)
        self.assertIn("function metricSlot", exporter)
        self.assertIn("contentFrame.metricGroupId = metricKey", exporter)
        self.assertIn("contentFrame.layoutRole = 'metric-label'", exporter)
        self.assertIn("contentFrame.layoutRole = 'metric-value'", exporter)
        self.assertIn("contentFrame.layoutRole = 'metric-change'", exporter)
        self.assertIn("function layoutMetricGroups", app)
        self.assertIn("cursor=y+item.layout.height+gap", app)
        self.assertIn("metricSlot:'label'", app)
        self.assertIn("metricSlot:'value'", app)
        self.assertIn("metricSlot:'change-row'", app)
        self.assertIn("o.english&&o.layout&&!o.mergedInto", app)
        self.assertIn('"metricGroupId"', package_schema)
        self.assertIn('"slot"', package_schema)
        self.assertIn('"layoutRole"', result_schema)

    def test_english_preview_has_undo_redo_history(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        styles = (ROOT / "styles.css").read_text()
        self.assertIn('id="undoEdit"', index)
        self.assertIn('id="redoEdit"', index)
        self.assertIn("undoHistory:new Map()", app)
        self.assertIn("redoHistory:new Map()", app)
        self.assertIn("function rememberEdit", app)
        self.assertIn("function undoEdit", app)
        self.assertIn("function redoEdit", app)
        self.assertIn("rememberEdit();object.english=value", app)
        self.assertIn("rememberEdit();object.lineBreakMode=mode", app)
        self.assertIn("if(moved){state.editorSession=null;rememberEdit()", app)
        self.assertIn("rememberEdit();const mergedFrom=", app)
        self.assertIn("preview-actions", styles)

    def test_text_inspector_edits_existing_semantic_objects(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        styles = (ROOT / "styles.css").read_text()
        for element_id in [
            "textInspector", "editText", "editFontFamily", "editFontSize",
            "editFontWeight", "editColor", "editLineHeight",
            "editLetterSpacing", "horizontalAlignment", "verticalAlignment",
            "editRotation", "editX", "editY", "editWidth", "editHeight",
            "editLineBreakMode", "selectionCount", "inspectorUndo",
            "resetGenerated", "resetSourceStyle", "cancelInspector",
            "applyInspector",
        ]:
            self.assertIn(f'id="{element_id}"', index)
        self.assertIn("function semanticCategory", app)
        self.assertIn("function updateInspectorField", app)
        self.assertIn("item.category===object.category", app)
        self.assertIn("manualSelection:new Set()", app)
        self.assertIn("event.shiftKey", app)
        self.assertIn("input[name=\"editScope\"]", app)
        self.assertIn("function commonValue", app)
        self.assertIn("class=\"editing-studio\"", index)
        self.assertIn("class=\"gallery-workspace\"", index)
        self.assertIn('id="openEditor"', index)
        self.assertIn('id="exitEditor"', index)
        self.assertIn("editorOpen:false", app)
        self.assertIn("function enterEditor", app)
        self.assertIn("function exitEditor", app)
        self.assertIn("if(!state.editorOpen){enterEditor(object);return}", app)
        self.assertIn("editing-mode", styles)
        self.assertIn('class="inspector-section"', index)
        self.assertIn("grid-column:2", styles)
        self.assertIn("max-width:min(100%,760px)", styles)
        self.assertIn("data-value=\"left\"", index)
        self.assertIn("aria-label=\"Align center\"", index)
        self.assertIn("function resetSelectedGenerated", app)
        self.assertIn("function resetSelectedSourceStyle", app)
        self.assertIn('transform="rotate(', app)
        self.assertIn("vertical==='middle'", app)
        self.assertIn("category:o.category", app)
        self.assertIn("rotation:o.rotation||0", app)
        self.assertIn(".text-inspector", styles)
        self.assertIn('Text-box width (px)<input id="editWidth"', index)
        self.assertIn("Number(item.translationLayout?.width)>0", app)
        self.assertIn("object.translationLayout={...object.translationLayout,mode,width", app)

    def test_design_tool_transform_handles_and_text_glyph_strokes(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        styles = (ROOT / "styles.css").read_text()
        for element_id in [
            "editBorderEnabled", "editBorderColor", "editBorderWidth",
            "editBorderStyle", "editBorderOpacity", "editStrokeAlignment",
        ]:
            self.assertIn(f'id="{element_id}"', index)
        self.assertIn("Text outline and fill", index)
        self.assertNotIn("Text-box border and fill", index)
        self.assertIn("function transformHandles", app)
        self.assertIn('data-handle="rotate"', app)
        self.assertIn("if(move.shiftKey)rotation=Math.round(rotation/15)*15", app)
        self.assertIn("if(move.shiftKey&&handle.length===2)", app)
        self.assertIn("reflowEditable(object,{preserveHeight:true})", app)
        self.assertIn("function withTextStrokes", app)
        self.assertIn("paint-order", app)
        self.assertIn("stroke-width", app)
        self.assertIn("group.querySelector('.actual-text-border')?.remove()", app)
        self.assertIn("transform-handle", styles)
        self.assertIn(".english-object.selected>.transform-handle{pointer-events:all!important}", styles)
        self.assertIn("event.target.closest('[data-handle]')", app)
        self.assertIn("combined-selection", styles)
        importer = (ROOT / "illustrator/apply-chartlingo-result.jsx").read_text()
        self.assertIn("characterAttributes.strokeColor", importer)
        self.assertIn("characterAttributes.strokeWeight", importer)
        self.assertNotIn("pathItems.roundedRectangle", importer)

    def test_multi_selection_alignment_toolbar_and_direct_positioning(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        styles = (ROOT / "styles.css").read_text()
        self.assertIn('id="multiAlignTools"', index)
        for action in ["top", "vcenter", "bottom"]:
            self.assertIn(f'data-align-action="{action}"', index)
        self.assertEqual(index.count('class="align-guide"'), 3)
        self.assertIn(".alignment-toolbar button svg", styles)
        for action in ["left", "hcenter", "right", "distribute-h", "distribute-v"]:
            self.assertNotIn(f'data-align-action="{action}"', index)
        self.assertNotIn("Position and text box", index)
        self.assertIn("function alignSelection", app)
        self.assertIn("function updateAlignmentToolbar", app)
        self.assertIn("selected.length<2", app)
        self.assertIn("alignSelection(button.dataset.alignAction)", app)
        self.assertIn("button.setAttribute('aria-pressed','true')", app)
        self.assertIn(".multi-align-tools[hidden]", styles)
        self.assertIn(".alignment-toolbar button:disabled", styles)

    def test_multi_selection_moves_as_a_group_and_supports_keyboard_nudging(self):
        app = (ROOT / "app.js").read_text()
        styles = (ROOT / "styles.css").read_text()
        self.assertIn('data-group-selection="true"', app)
        self.assertIn("function selectedBounds", app)
        self.assertIn("function constrainedSelectionDelta", app)
        self.assertIn("function moveSelectedBy", app)
        self.assertIn("function bindGroupMovement", app)
        self.assertIn("origin.x+last.dx", app)
        self.assertIn("origin.y+last.dy", app)
        self.assertIn("spec.width-bounds.right", app)
        self.assertIn("spec.naturalHeight-bounds.bottom", app)
        self.assertIn("ArrowLeft", app)
        self.assertIn("event.shiftKey?10:1", app)
        self.assertIn("state.manualSelection.clear()", app)
        self.assertIn("pointer-events:all;cursor:move", styles)

    def test_removed_preflight_ui_and_invalid_svg_control_characters(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        styles = (ROOT / "styles.css").read_text()
        self.assertNotIn(">Run checks<", index)
        self.assertNotIn("issues-panel", index)
        self.assertNotIn("<h2>Exceptions</h2>", index)
        self.assertIn('id="statusSummary" hidden', index)
        self.assertIn('id="issues" hidden', index)
        self.assertIn("\\u0000-\\u0008", app)
        self.assertIn("documentNode.querySelector('parsererror')", app)
        self.assertIn(".lower-grid{grid-template-columns:minmax(0,1fr)}", styles)

    def test_editor_can_toggle_chinese_reference_without_scope_or_reset_ui(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        styles = (ROOT / "styles.css").read_text()
        self.assertNotIn("<summary>Edit scope</summary>", index)
        self.assertNotIn(">Selected text only<", index)
        self.assertNotIn(">Reset generated<", index)
        self.assertNotIn(">Reset style<", index)
        self.assertNotIn(">Cancel<", index)
        self.assertIn('id="toggleReference"', index)
        self.assertIn('id="editorReferencePanel"', index)
        self.assertIn('id="editorSourceCanvas"', index)
        self.assertIn("showReference:false", app)
        self.assertIn("state.showReference=!state.showReference", app)
        self.assertIn("state.showReference?'Hide Chinese reference':'Show Chinese reference'", app)
        self.assertIn("show-reference .editing-studio", styles)
        self.assertIn("show-reference .editor-reference-panel", styles)

    def test_editor_back_replaces_artboard_tab_apply_moves_to_toolbar_and_mappings_hide(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        styles = (ROOT / "styles.css").read_text()
        self.assertIn("if(state.editorOpen){const back=document.createElement('button')", app)
        self.assertIn("back.textContent='← Back to gallery'", app)
        self.assertIn("renderTabs();renderCanvases();renderInspector()", app)
        toolbar = index[index.index('class="preview-actions"'):index.index('</div></div>', index.index('class="preview-actions"'))]
        self.assertLess(toolbar.index('id="redoEdit"'), toolbar.index('id="applyInspector"'))
        self.assertIn('class="lower-grid" hidden', index)
        self.assertIn(".lower-grid[hidden]{display:none!important}", styles)
        self.assertIn("#app.editing-mode #applyInspector{display:inline-flex}", styles)

    def test_top_toolbar_groups_import_generate_and_export_dropdown(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        styles = (ROOT / "styles.css").read_text()
        top_actions = index[index.index('<div class="top-actions">'):index.index('</div>\n  </header>')]
        self.assertIn('id="packageInput"', top_actions)
        self.assertIn('id="csvInput"', top_actions)
        self.assertIn('id="generate" class="button primary"', top_actions)
        self.assertIn('class="toolbar-divider"', top_actions)
        self.assertIn('class="export-menu"', top_actions)
        self.assertIn('id="exportSvg"', top_actions)
        self.assertIn('id="exportPng"', top_actions)
        self.assertIn('id="exportResult"', top_actions)
        self.assertIn(".export-menu-popover", styles)
        self.assertIn(".export-option", styles)
        self.assertIn("removeAttribute('open')", app)
        self.assertIn('class="projectbar" hidden', index)
        self.assertIn(".projectbar[hidden]{display:none!important}", styles)
        self.assertIn("#app:not(.editing-mode) .canvas-host svg{width:auto;max-width:100%;height:auto;max-height:70vh}", styles)

    def test_illustrator_tab_tables_export_as_independent_cells(self):
        exporter = (ROOT / "illustrator/export-to-chartlingo.jsx").read_text()
        importer = (ROOT / "illustrator/apply-chartlingo-result.jsx").read_text()
        self.assertIn("function tableRows", exporter)
        self.assertIn("numbered.numberedList = true", exporter)
        self.assertIn("plain.length >= 3", exporter)
        self.assertIn("plain.plainList = true", exporter)
        self.assertIn("function pairedAxisLabels", exporter)
        self.assertIn("result.push({year: first[i], period: second[i]})", exporter)
        self.assertIn("kind: 'axis-year'", exporter)
        self.assertIn("kind: 'axis-period'", exporter)
        self.assertIn("'-x' + (columnIndex + 1) + '-year'", exporter)
        self.assertIn("'-x' + (columnIndex + 1) + '-period'", exporter)
        self.assertIn("groupId: groupId", exporter)
        self.assertIn("fieldType: 'year'", exporter)
        self.assertIn("axisField: 'year'", exporter)
        self.assertIn("axisField: fieldType", exporter)
        self.assertIn("function creditLines", exporter)
        self.assertIn("kind: 'credit-line'", exporter)
        self.assertIn("itemId = baseId + '-' + fieldType", exporter)
        self.assertIn("fieldType: fieldType", exporter)
        self.assertIn("-x\\d+-(?:year|period)", importer)
        self.assertIn("rows.plainList ? 'list-item' : 'table-cell'", exporter)
        self.assertIn("rows.numberedList", exporter)
        self.assertIn("width * 0.28", exporter)
        self.assertIn("function tableColumns", exporter)
        self.assertIn("x: anchors[i]", exporter)
        self.assertNotIn("(anchors[i - 1] + anchors[i]) / 2", exporter)
        self.assertIn("'-r' + (rowIndex + 1) + '-c' + (columnIndex + 1)", exporter)
        self.assertIn("'list-item' : 'table-cell'", exporter)
        self.assertIn("candidate.kind === 'list-item'", exporter)
        self.assertIn("virtualCell: true", exporter)
        self.assertIn("sourceFrameId(sourceId)", importer)

    def test_legacy_packages_warn_instead_of_failing(self):
        core = (ROOT / "core.js").read_text()
        app = (ROOT / "app.js").read_text()
        self.assertIn("copy.legacyExporter=", core)
        self.assertIn("CLV2.removeLegacyOutlinedText", core)
        self.assertIn("fill===target.color", core)
        self.assertIn("CLV2.removeLegacyOutlinedText(packaged||sourceSvg(board),board.textFrames)", app)
        self.assertIn("Older package imported", app)
        self.assertIn("LEGACY_EXPORTER", app)
        self.assertNotIn("This package was made by an older Illustrator exporter", core)

    def test_original_application_paths_are_not_referenced_for_writes(self):
        for path in ROOT.rglob("*"):
            if path.is_file() and path.suffix in {".js", ".jsx", ".html"}:
                text = path.read_text(errors="ignore")
                self.assertNotIn("../src/", text)
                self.assertNotIn("../index.html", text)


if __name__ == "__main__":
    unittest.main()
