import json
import pathlib
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[1]


class ChartLingoTests(unittest.TestCase):
    def test_product_name_is_chartlingo(self):
        index = (ROOT / "index.html").read_text()
        exporter = (ROOT / "illustrator/export-to-chartlingo.jsx").read_text()
        self.assertIn("<title>ChartLingo</title>", index)
        self.assertIn("<span>ChartLingo</span>", index)
        self.assertIn("ChartLingo — Export", exporter)
        self.assertNotIn("ChartLingoV2", index)
        self.assertNotIn("ChartLingoV2", exporter)

    def test_v2_is_self_contained(self):
        for name in ["index.html", "styles.css", "core.js", "app.js", "README.md"]:
            self.assertTrue((ROOT / name).is_file(), name)

    def test_workspace_placeholders_replace_intro_page(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        self.assertNotIn('id="emptyState"', index)
        self.assertIn('<section id="app">', index)
        self.assertIn('class="panel-placeholder"', index)
        self.assertIn('No package loaded', index)
        self.assertNotIn("$('emptyState')", app)

    def test_schema_contracts_are_versioned(self):
        package = json.loads((ROOT / "schemas/package-v2.schema.json").read_text())
        result = json.loads((ROOT / "schemas/result-v2.schema.json").read_text())
        self.assertEqual(package["$id"], "https://chartlingo.local/schemas/package-v2.json")
        self.assertEqual(result["$id"], "https://chartlingo.local/schemas/result-v2.json")
        self.assertEqual(package["properties"]["schemaVersion"]["const"], "2.0.0")
        self.assertEqual(result["properties"]["schemaVersion"]["const"], "2.0.0")

    def test_multiline_text_is_one_source_object(self):
        core = (ROOT / "core.js").read_text()
        self.assertIn("visibleLines:['航程缩短3小时，','新加坡经济可获什么？']", core)
        self.assertIn("sourceText:'航程缩短3小时，新加坡经济可获什么？'", core)
        self.assertEqual(core.count("id:'headline-01'"), 1)

    def test_axis_and_credit_fields_are_atomic_data_records(self):
        core = (ROOT / "core.js").read_text()
        app = (ROOT / "app.js").read_text()
        package_schema = (ROOT / "schemas/package-v2.schema.json").read_text()
        result_schema = (ROOT / "schemas/result-v2.schema.json").read_text()
        self.assertIn("CLV2.atomicTextFrames", core)
        self.assertIn("sourceText:lines[0]", core)
        self.assertIn("sourceText:lines[1]", core)
        self.assertIn("CLV2.atomicTextFrames(board.textFrames)", core)
        self.assertIn("board.textFrames=CLV2.splitNumericAxes", core)
        self.assertIn("data-group-id", app)
        self.assertIn("data-field-type", app)
        self.assertIn('"groupId"', package_schema)
        self.assertIn('"fieldType"', package_schema)
        self.assertIn('"pairId"', result_schema)

    def test_direct_exports_exist(self):
        app = (ROOT / "app.js").read_text()
        self.assertIn("function exportSvg()", app)
        self.assertIn("function exportPng()", app)
        self.assertNotIn("function exportResult()", app)
        self.assertTrue((ROOT / "illustrator/export-to-chartlingo.jsx").is_file())
        self.assertTrue((ROOT / "illustrator/apply-chartlingo-result.jsx").is_file())

    def test_svg_export_is_illustrator_compatible_xml(self):
        app = (ROOT / "app.js").read_text()
        self.assertIn("function illustratorCompatibleSvg", app)
        self.assertIn("ILLUSTRATOR_SVG_DOCTYPE", app)
        self.assertIn("<!ENTITY ns_extend", app)
        self.assertIn("<!ENTITY ns_ai", app)
        self.assertIn("<!ENTITY ns_graphs", app)
        self.assertIn("encoding=\"UTF-8\"", app)
        self.assertIn("xmlns:a", app)
        self.assertIn("embedded=await validateAndEmbedExportImages(decorated,board())", app)
        self.assertIn("svg=illustratorCompatibleSvg(embedded)", app)
        self.assertIn("SVG export validation failed after Illustrator compatibility processing", app)

    def test_svg_export_embeds_and_validates_every_raster_image(self):
        app = (ROOT / "app.js").read_text()
        exporter = (ROOT / "illustrator/export-to-chartlingo.jsx").read_text()
        self.assertIn("function validateAndEmbedExportImages", app)
        self.assertIn("function imageExportFailure", app)
        self.assertIn("data:image\\/(jpeg|png|webp);base64", app)
        self.assertIn("image.setAttribute('href',normalized)", app)
        self.assertIn("image.setAttributeNS('http://www.w3.org/1999/xlink','xlink:href',normalized)", app)
        self.assertIn("xmlns:xlink", app)
        self.assertIn("The browser could not decode the embedded image", app)
        self.assertIn("External and local image links are not allowed", app)
        self.assertIn("imageExports", app)
        self.assertIn("function invalidSvgImageReason", exporter)
        self.assertIn("options.embedRasterImages = true", exporter)
        self.assertIn("Embedding photos and preserving vectors", exporter)
        self.assertIn("OPTIMIZED_IMAGE_PPI = 100", exporter)
        self.assertIn("OPTIMIZED_JPEG_QUALITY = 80", exporter)
        self.assertIn("function rasterizeDisplayedPhotos", exporter)
        self.assertIn("function restoreRasterizedPhotos", exporter)
        self.assertIn("new ExportOptionsJPEG()", exporter)
        self.assertIn("options.qualitySetting = OPTIMIZED_JPEG_QUALITY", exporter)
        self.assertIn("options.horizontalScale = OPTIMIZED_IMAGE_PPI / 72 * 100", exporter)
        self.assertIn("restoreRasterizedPhotos(rasterStates)", exporter)
        self.assertIn("function duplicateLogoOnTop", exporter)
        self.assertIn("ZOrderMethod.BRINGTOFRONT", exporter)
        self.assertIn("removeTemporaryTopLogo(logoState)", exporter)
        self.assertIn("removeTemporaryTree(temporaryFolder)", exporter)
        self.assertIn("readArtworkWithoutLiveText(artboards[i].index, artboards[i], exportChoice.imageMode === 'optimized')", exporter)
        self.assertIn("jsonStringify(data, '', 0)", exporter)
        self.assertIn("imageExportDiagnostics", exporter)
        self.assertIn("vectorsPreserved: true", exporter)
        self.assertIn("usedRasterFallback: false", exporter)

    def test_browser_exports_require_a_system_save_confirmation(self):
        app = (ROOT / "app.js").read_text()
        self.assertIn("window.showSaveFilePicker", app)
        self.assertIn("function chooseExportDestination", app)
        self.assertIn("function saveExport", app)
        self.assertIn("if(error?.name==='AbortError')", app)
        self.assertNotIn("function download", app)
        self.assertIn("unsupported:true", app)
        self.assertIn("The export was not created", app)
        self.assertIn("id:'chartlingo-export-location'", app)
        self.assertNotIn("window.showDirectoryPicker", app)
        self.assertNotIn("exportDirectoryHandle", app)
        self.assertNotIn("destination.directory.getFileHandle", app)
        self.assertEqual(app.count("window.showSaveFilePicker"), 2)
        self.assertNotIn('id="changeExportFolder"', (ROOT / "index.html").read_text())
        for extension in ["svg", "png", "jpg"]:
            self.assertIn(f"chooseExportDestination(name,'{extension}')", app)

    def test_embedded_svg_is_sanitized(self):
        core = (ROOT / "core.js").read_text()
        self.assertIn("CLV2.sanitizeSvg", core)
        self.assertIn("CLV2.stripInvalidXmlCharacters", core)
        self.assertIn("Removed ${removed} invalid SVG control character", core)
        self.assertIn("CLV2.normalizeAdobeSvgNamespaces", core)
        self.assertIn("&ns_extend;", core)
        self.assertIn("http://ns.adobe.com/AdobeIllustrator/10.0/", core)
        self.assertIn("script,foreignObject,iframe,object,embed,audio,video", core)
        self.assertIn("name.startsWith('on')", core)

    def test_exporter_repairs_adobe_svg_namespace_entities(self):
        exporter = (ROOT / "illustrator/export-to-chartlingo.jsx").read_text()
        self.assertIn("function normalizeAdobeSvgNamespaces", exporter)
        self.assertIn("function stripInvalidXmlCharacters", exporter)
        self.assertIn("stripInvalidXmlCharacters(normalizeAdobeSvgNamespaces(value))", exporter)
        self.assertIn("version: '0.8.7'", exporter)

    def test_text_box_resize_previews_live_text_reflow(self):
        app = (ROOT / "app.js").read_text()
        self.assertIn("function editableReflowLines", app)
        self.assertIn("function previewTextBoxReflow", app)
        self.assertIn("previewTextBoxReflow(node,object,preview)", app)
        self.assertIn("text.replaceChildren", app)
        self.assertIn("state.manualSelection.size===1?object.layout:visualTextBounds(object)", app)
        self.assertIn("if(message==='Text box resized and text reflowed.')return", app)

    def test_fixed_1200_by_800_output_is_opt_in_per_artboard(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        self.assertIn('id="outputSizeMode"', index)
        self.assertIn('value="auto">Auto height', index)
        self.assertIn('value="fixed">Fixed 1200 × 800', index)
        self.assertIn("outputModes:new Map()", app)
        self.assertIn("fixedOutputTransforms:new Map()", app)
        self.assertIn("state.outputModes.get(artboard.id)==='fixed'", app)
        self.assertIn("fixedHeight=800", app)
        self.assertIn("800/previous.height", app)
        self.assertIn("centerY-previous.cropTop*ratio", app)
        self.assertIn("function changeOutputSizeMode", app)
        self.assertIn("$('outputSizeMode').onchange", app)

    def test_exporter_joins_fragmented_decimal_axis_lines(self):
        core = (ROOT / "core.js").read_text()
        exporter = (ROOT / "illustrator/export-to-chartlingo.jsx").read_text()
        self.assertIn("CLV2.mergeSpatialDecimalTicks", core)
        self.assertIn("vertical>tolerance", core)
        self.assertIn("aligned.length<3", core)
        self.assertIn("function joinedNumericAxisLines", exporter)
        self.assertIn("lines.push(parts[i] + parts[i + 1])", exporter)
        self.assertIn("return joinedNumericAxisLines", exporter)

    def test_illustrator_scripts_do_not_require_native_json(self):
        exporter = (ROOT / "illustrator/export-to-chartlingo.jsx").read_text()
        importer = (ROOT / "illustrator/apply-chartlingo-result.jsx").read_text()
        self.assertIn("function jsonStringify", exporter)
        self.assertIn("function jsonParse", importer)
        self.assertNotIn("JSON.stringify", exporter)
        self.assertNotIn("JSON.parse", importer)

    def test_v2_removes_source_text_and_uses_1200px_output(self):
        core = (ROOT / "core.js").read_text()
        app = (ROOT / "app.js").read_text()
        self.assertIn("CLV2.removeSourceText", core)
        self.assertIn("querySelectorAll('text,textPath,flowRoot,flowPara')", core)
        self.assertIn("const width=1200", app)
        self.assertIn("sourceWidth=Number(artboard.bounds.width)", app)
        self.assertIn("naturalHeight=fixed?fixedHeight:Math.round(contentHeight)", app)
        self.assertIn('transform="translate(0 ${-spec.cropTop}) scale(${spec.scale})"', app)
        self.assertNotIn("source-masks", app)
        self.assertNotIn("source-mask", app)

    def test_unmatched_text_is_retained_and_roboto_is_bundled(self):
        core = (ROOT / "core.js").read_text()
        app = (ROOT / "app.js").read_text()
        self.assertIn("pair?.en||frame.sourceText", core)
        self.assertIn("sourceRetained:!pair", core)
        self.assertIn("function updateMapping", app)
        self.assertIn("Use original Chinese content", app)
        self.assertIn("manual-match", app)
        self.assertIn("if(score<.82)pair=null", core)
        self.assertTrue((ROOT / "fonts/Roboto-Regular.ttf").is_file())
        self.assertTrue((ROOT / "fonts/Roboto-Bold.ttf").is_file())
        self.assertTrue((ROOT / "fonts/OFL.txt").is_file())

    def test_generated_text_can_be_dragged_and_exported_at_new_position(self):
        app = (ROOT / "app.js").read_text()
        styles = (ROOT / "styles.css").read_text()
        self.assertIn("function bindCanvasDragging", app)
        self.assertIn("node.onpointerdown", app)
        self.assertIn("item.layout.x=base.x+dx", app)
        self.assertIn("item.layout.y=base.y+dy", app)
        self.assertIn("moveTargets.some(item=>item.originalSource?.role==='TITLE'||item.source?.role==='TITLE')", app)
        self.assertIn("function toast(message){if(state.editorOpen)return", app)
        self.assertIn("cursor:grab", styles)

    def test_reference_title_style_and_source_locked_geometry(self):
        core = (ROOT / "core.js").read_text()
        app = (ROOT / "app.js").read_text()
        exporter = (ROOT / "illustrator/export-to-chartlingo.jsx").read_text()
        self.assertIn("CLV2.originalLayout", core)
        self.assertIn("sourceLocked:true", core)
        self.assertIn("function referenceTitleFrame", app)
        self.assertIn("x:147.73046875*scale", app)
        self.assertIn("y:106.2744140625*scale", app)
        self.assertIn("fontSize=65*scale", app)
        self.assertIn("fontWeight:700", app)
        self.assertIn("object.numericLocked||object.sourceRetained||object.source.referenceMatched", app)
        self.assertIn("candidate.bounds.y > artboards[i].bounds.height * 0.25", exporter)
        self.assertIn("titleCandidate.style.fontWeight = 700", exporter)

    def test_per_chart_reference_package_drives_translated_geometry(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        self.assertNotIn('id="referenceInput"', index)
        self.assertNotIn('id="loadSample"', index)
        self.assertIn("referencePkg:null", app)
        self.assertIn("function referenceFrame", app)
        self.assertIn("referenceKey(item.sourceText)===referenceKey(english)", app)
        self.assertIn("referenceMatched:true", app)
        self.assertIn("object.source.referenceMatched", app)
        self.assertIn("independent translation widths and structured metric groups", app)

    def test_reference_credits_have_an_eight_pixel_floor_and_wrap(self):
        app = (ROOT / "app.js").read_text()
        self.assertIn("function isCredit", app)
        self.assertIn("function isGraphicCredit", app)
        self.assertIn("zaobao\\s+(?:graphic|chart)", app)
        self.assertIn("fontSize=credit?28:", app)
        self.assertIn("x:60,width:spec.width-120", app)
        self.assertIn("height:48", app)
        self.assertIn("visibleLines=credit?[english]", app)

    def test_output_height_auto_fits_content(self):
        app = (ROOT / "app.js").read_text()
        self.assertIn("const width=1200", app)
        self.assertIn("cropWindows:new Map()", app)
        self.assertIn("function fitCropWindow", app)
        self.assertIn("contentTop-ARTBOARD_PADDING", app)
        self.assertIn("contentBottom+ARTBOARD_PADDING", app)
        self.assertIn("expandOnly&&previous", app)
        self.assertIn("cropBottom-cropTop", app)
        self.assertIn('id="english-layer" transform="translate(0 ${-spec.cropTop})"', app)

    def test_plain_list_labels_share_a_font_size(self):
        app = (ROOT / "app.js").read_text()
        self.assertIn("function normalizeListTypography", app)
        self.assertIn("let fontSize=26", app)
        self.assertIn("while(fontSize>18", app)
        self.assertIn("fontSize,1", app)
        self.assertIn("fontSize,2", app)
        self.assertIn("normalizeListTypography(list)", app)

    def test_headline_moves_instead_of_disconnecting_chart_content(self):
        app = (ROOT / "app.js").read_text()
        self.assertIn("contentShifts:new Map()", app)
        self.assertIn("function enforceHeaderGap", app)
        self.assertIn("contentTop-HEADER_CONTENT_GAP-title.layout.height", app)
        self.assertIn("enforceHeaderGap(artboard,list)", app)
        self.assertNotIn('stroke="#b8b8b8"', app)
        self.assertIn('transform="translate(0 ${-spec.cropTop}) scale(${spec.scale})"', app)
        self.assertNotIn("item.layout.y+shift", app)
        self.assertNotIn("titleLimit=", app)
        self.assertNotIn("visibleTop=spec.cropTop", app)
        self.assertIn("item.layout.y=base.y+dy", app)
        self.assertIn("Text position updated.", app)

    def test_header_and_credits_use_uploaded_reference_spec(self):
        app = (ROOT / "app.js").read_text()
        self.assertIn("147.73046875*scale", app)
        self.assertIn("106.2744140625*scale", app)
        self.assertIn("fontSize=65*scale", app)
        self.assertIn("function referenceCreditFrame", app)
        self.assertIn("43.66015625*scale", app)
        self.assertIn("y:frame.bounds.y", app)
        self.assertIn("fontSize:28*scale", app)
        self.assertIn("visibleLines:[english]", app)

    def test_untranslated_numbers_use_proportional_source_geometry(self):
        app = (ROOT / "app.js").read_text()
        self.assertIn("function isNumericContent", app)
        self.assertIn("function mappedBounds", app)
        self.assertIn("sourceWidth=Number(artboard.bounds.width)", app)
        self.assertIn("scaleX=width/sourceWidth", app)
        self.assertIn("numericLocked=mapping.sourceRetained&&isNumericContent", app)
        self.assertIn("method:numericLocked?'source coordinates'", app)
        self.assertNotIn("method:numericReference?'reference cell'", app)

    def test_strict_positions_and_browser_text_removal(self):
        core = (ROOT / "core.js").read_text()
        app = (ROOT / "app.js").read_text()
        exporter = (ROOT / "illustrator/export-to-chartlingo.jsx").read_text()
        self.assertIn("x=frame.bounds.x,y=frame.bounds.y", core)
        self.assertIn("sourceRetained&&original.visibleLines?.length>1", app)
        self.assertIn("artboards[i].artworkSvg = null", exporter)
        self.assertIn("CLV2.removeSourceText", core)
        self.assertIn("version: '0.6.4'", exporter)

    def test_illustrator_exporter_exports_only_active_artboard(self):
        exporter = (ROOT / "illustrator/export-to-chartlingo.jsx").read_text()
        self.assertNotIn("function chooseArtboards", exporter)
        self.assertNotIn("All artboards in one package", exporter)
        self.assertNotIn("Specific range in one package", exporter)
        self.assertNotIn("Each artboard as a separate package", exporter)
        self.assertIn("activeArtboardIndex = doc.artboards.getActiveArtboardIndex()", exporter)
        self.assertIn("selectedIndices = [activeArtboardIndex]", exporter)
        self.assertIn("exportMode: 'selected'", exporter)
        self.assertIn("function artboardFor(bounds)", exporter)
        self.assertIn("area > bestArea", exporter)
        self.assertIn("if (boardIndex < 0", exporter)
        self.assertIn("options.artboardRange = String(artboardIndex + 1)", exporter)
        self.assertIn("previewSvg: null, artworkSvg: null", exporter)
        self.assertIn("artboards[i].previewSvg = readSvg(artboards[i].index)", exporter)
        self.assertIn("position: {x: rect[0], y: rect[1]}", exporter)
        self.assertIn("orientation: width >= height ? 'landscape' : 'portrait'", exporter)
        self.assertIn("new Window('palette', 'ChartLingo Export')", exporter)
        self.assertIn("Cancel export", exporter)
        self.assertIn("function progress(stage, current, total, artboardName)", exporter)
        self.assertIn("artboards[i].previewSvg = readSvg(artboards[i].index)", exporter)
        self.assertIn("artboards[i].artworkSvg = null", exporter)
        self.assertNotIn("function readArtworkWithoutLiveText", exporter)
        self.assertNotIn("doc.groupItems.length", exporter)
        self.assertIn("__CHARTLINGO_CANCELLED__", exporter)

    def test_logo_safe_credit_layout_is_exported_and_dynamic(self):
        app = (ROOT / "app.js").read_text()
        exporter = (ROOT / "illustrator/export-to-chartlingo.jsx").read_text()
        schema = (ROOT / "schemas/package-v2.schema.json").read_text()
        self.assertNotIn("function logoBoundsForArtboard", exporter)
        self.assertIn("logoBounds: null", exporter)
        self.assertIn('"logoBounds"', schema)
        self.assertIn("function scaledLogoBounds", app)
        self.assertIn("function layoutBottomCredits", app)
        self.assertIn("logo.x-logoMargin", app)
        self.assertIn("CLV2.wrap(item.english,width,preferred,8)", app)
        self.assertIn("previousBottom+8", app)

    def test_chart_content_line_break_modes_are_scoped(self):
        core = (ROOT / "core.js").read_text()
        app = (ROOT / "app.js").read_text()
        exporter = (ROOT / "illustrator/export-to-chartlingo.jsx").read_text()
        package_schema = (ROOT / "schemas/package-v2.schema.json").read_text()
        result_schema = (ROOT / "schemas/result-v2.schema.json").read_text()
        styles = (ROOT / "styles.css").read_text()
        self.assertIn("function isChartContent", app)
        self.assertIn("function updateLineBreakMode", app)
        self.assertIn('<option value="auto"', app)
        self.assertIn('<option value="single-line"', app)
        self.assertIn("Manual line breaks", app)
        self.assertIn("Match source layout", app)
        self.assertIn("function updateTranslationWidth", app)
        self.assertIn("translation-width", styles)
        self.assertIn("function independentWidth", app)
        self.assertIn("inheritSourceWidth", app)
        self.assertIn('"match-source"', package_schema)
        self.assertIn('"translationLayout"', result_schema)
        self.assertIn("CLV2.fixedLinesLayout", core)
        self.assertIn("frame.bounds.width", core)
        self.assertIn("contentFrame.contentType = 'chart'", exporter)
        self.assertIn("contentFrame.lineBreakMode = 'auto'", exporter)
        self.assertIn("contentFrame.translationLayout", exporter)
        self.assertIn('"lineBreakMode"', package_schema)
        self.assertIn('"manualLines"', result_schema)
        self.assertIn("line-break-control", styles)

    def test_chart_content_can_merge_and_regenerate_from_csv(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        importer = (ROOT / "illustrator/apply-chartlingo-result.jsx").read_text()
        schema = (ROOT / "schemas/result-v2.schema.json").read_text()
        styles = (ROOT / "styles.css").read_text()
        self.assertIn('id="mergeSelected"', index)
        self.assertIn('id="mergeCsvField"', index)
        self.assertIn("function mergeSelectedFromCsv", app)
        self.assertIn("mergedFrom=ordered.flatMap", app)
        self.assertIn("csvField:pair.ch", app)
        self.assertIn("method:'merged CSV field'", app)
        self.assertIn("function automaticStyleReference", app)
        self.assertIn("function structuralStyleRole", app)
        self.assertIn("function selectedStyleRole", app)
        self.assertIn("function styleSignature", app)
        self.assertIn("sameRow*100000+dominance*1000", app)
        self.assertIn("styleSource=manualStyle||automaticStyleReference", app)
        self.assertIn("baseSize=frame.style.fontSize||14", app)
        self.assertIn("style:{...styleSource.source.style}", app)
        self.assertNotIn("fontSize=median(stylePool.map", app)
        self.assertIn("styleReferenceId:styleSource.frameId", app)
        self.assertIn("styleRole,metricGroupId,slot,inheritStyle:true", app)
        self.assertIn("inheritStyle:true", app)
        self.assertIn("MERGED_MAX_SHRINK=.9", app)
        self.assertIn("sameColumnBelow=objects().filter", app)
        self.assertIn("item.layout.x<right&&item.layout.x+item.layout.width>left", app)
        self.assertIn("function mergedAutoLayout", app)
        self.assertIn("!o.mergedInto", app)
        self.assertIn("change.mergedFrom && change.mergedFrom.length", importer)
        self.assertIn("change.layout.lines.join('\\r')", importer)
        self.assertIn('"mergedFrom"', schema)
        self.assertIn('"csvField"', schema)
        self.assertIn('"styleReferenceId"', schema)
        self.assertIn('"styleRole"', schema)
        self.assertIn('"inheritStyle"', schema)
        self.assertIn("mapping-row.merged", styles)

    def test_infographic_text_is_atomic_and_vector_artwork_uses_fast_svg_export(self):
        exporter = (ROOT / "illustrator/export-to-chartlingo.jsx").read_text()
        app = (ROOT / "app.js").read_text()
        package_schema = (ROOT / "schemas/package-v2.schema.json").read_text()
        result_schema = (ROOT / "schemas/result-v2.schema.json").read_text()
        self.assertIn("function graphicTextType", exporter)
        self.assertIn("'graphic-value'", exporter)
        self.assertIn("'graphic-percentage'", exporter)
        self.assertIn("graphicElements: []", exporter)
        self.assertNotIn("for (graphicIndex = 0; graphicIndex < doc.pathItems.length", exporter)
        self.assertIn("Vector artwork remains inside previewSvg", exporter)
        self.assertIn('"graphic-label"', package_schema)
        self.assertIn('"graphic-value"', package_schema)
        self.assertIn('"graphic-percentage"', package_schema)
        self.assertIn('"graphicElement"', package_schema)
        self.assertIn('"graphicElement"', result_schema)

    def test_infographic_metric_groups_use_non_overlapping_slots(self):
        exporter = (ROOT / "illustrator/export-to-chartlingo.jsx").read_text()
        app = (ROOT / "app.js").read_text()
        package_schema = (ROOT / "schemas/package-v2.schema.json").read_text()
        result_schema = (ROOT / "schemas/result-v2.schema.json").read_text()
        self.assertIn("function sourceGroupKey", exporter)
        self.assertIn("function metricSlot", exporter)
        self.assertIn("contentFrame.metricGroupId = metricKey", exporter)
        self.assertIn("contentFrame.layoutRole = 'metric-label'", exporter)
        self.assertIn("contentFrame.layoutRole = 'metric-value'", exporter)
        self.assertIn("contentFrame.layoutRole = 'metric-change'", exporter)
        self.assertIn("function layoutMetricGroups", app)
        self.assertIn("cursor=y+item.layout.height+gap", app)
        self.assertIn("metricSlot:'label'", app)
        self.assertIn("metricSlot:'value'", app)
        self.assertIn("metricSlot:'change-row'", app)
        self.assertIn('"metricGroupId"', package_schema)
        self.assertIn('"slot"', package_schema)
        self.assertIn('"layoutRole"', result_schema)

    def test_english_preview_has_undo_redo_history(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        styles = (ROOT / "styles.css").read_text()
        self.assertIn('id="undoEdit"', index)
        self.assertIn('id="redoEdit"', index)
        self.assertIn("undoHistory:new Map()", app)
        self.assertIn("redoHistory:new Map()", app)
        self.assertIn("function rememberEdit", app)
        self.assertIn("function undoEdit", app)
        self.assertIn("function redoEdit", app)
        self.assertIn("rememberEdit();object.english=value", app)
        self.assertIn("rememberEdit();object.lineBreakMode=mode", app)
        self.assertIn("if(moved){state.editorSession=null;rememberEdit()", app)
        self.assertIn("rememberEdit();const mergedFrom=", app)
        self.assertIn("preview-actions", styles)

    def test_text_inspector_edits_existing_semantic_objects(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        styles = (ROOT / "styles.css").read_text()
        for element_id in [
            "textInspector", "editText", "editFontFamily", "editFontSize",
            "editFontWeight", "editColor", "editLineHeight",
            "editLetterSpacing", "horizontalAlignment", "verticalAlignment",
            "editRotation", "editX", "editY", "editWidth", "editHeight",
            "editLineBreakMode", "selectionCount", "inspectorUndo",
            "resetGenerated", "resetSourceStyle", "cancelInspector",
        ]:
            self.assertIn(f'id="{element_id}"', index)
        self.assertIn("function semanticCategory", app)
        self.assertIn("function updateInspectorField", app)
        self.assertIn('id="inspectorEmptyState"', index)
        self.assertIn("panel.classList.add('no-selection')", app)
        self.assertIn("$('selectionCount').textContent='No item selected'", app)
        self.assertIn(".text-inspector.no-selection", styles)
        self.assertIn("item.category===object.category", app)
        self.assertIn("manualSelection:new Set()", app)
        self.assertIn("event.shiftKey", app)
        self.assertIn("input[name=\"editScope\"]", app)
        self.assertIn("function commonValue", app)
        self.assertIn("class=\"editing-studio\"", index)
        self.assertIn("class=\"gallery-workspace\"", index)
        self.assertIn('id="openEditor"', index)
        self.assertNotIn('id="exitEditor"', index)
        self.assertIn("editorOpen:false", app)
        self.assertIn("function enterEditor", app)
        self.assertIn("function exitEditor", app)
        self.assertIn("if(!state.editorOpen){enterEditor(object);return}", app)
        self.assertIn("editing-mode", styles)
        self.assertIn('class="inspector-section"', index)
        self.assertIn("grid-column:2", styles)
        self.assertIn("max-width:min(100%,760px)", styles)
        self.assertIn("data-value=\"left\"", index)
        self.assertIn("aria-label=\"Align center\"", index)
        self.assertIn("function resetSelectedGenerated", app)
        self.assertIn("function resetSelectedSourceStyle", app)
        self.assertIn('transform="rotate(', app)
        self.assertIn("vertical==='middle'", app)
        self.assertIn(".text-inspector", styles)
        self.assertIn('Text-box width (px)<input id="editWidth"', index)
        self.assertIn("Number(item.translationLayout?.width)>0", app)
        self.assertIn("object.translationLayout={...object.translationLayout,mode,width", app)

    def test_design_tool_transform_handles_and_text_glyph_strokes(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        styles = (ROOT / "styles.css").read_text()
        for element_id in [
            "editBorderEnabled", "editBorderColor", "editBorderWidth",
            "editBorderStyle", "editBorderOpacity", "editStrokeAlignment",
        ]:
            self.assertIn(f'id="{element_id}"', index)
        self.assertNotIn("Text-box border and fill", index)
        self.assertIn("function transformHandles", app)
        self.assertIn('data-handle="rotate"', app)
        self.assertIn("if(move.shiftKey)rotation=Math.round(rotation/15)*15", app)
        self.assertIn("if(move.shiftKey&&handle.length===2)", app)
        self.assertIn("reflowEditable(object,{preserveHeight:true})", app)
        self.assertNotIn("Text outline enabled", index)
        self.assertIn('id="partialHighlightTitle" hidden', index)
        self.assertIn('<option value="outside">Outside</option><option value="center">Center</option>', index)
        self.assertIn("alignment:'outside'", app)
        self.assertIn("item.stroke.enabled=enabled", app)
        self.assertIn(".highlight-rows{grid-template-columns:minmax(0,1fr) minmax(0,1fr)", styles)
        self.assertIn("function withTextStrokes", app)
        self.assertIn("paint-order", app)
        self.assertIn("stroke-width", app)
        self.assertIn("group.querySelector('.actual-text-border')?.remove()", app)
        self.assertIn("transform-handle", styles)
        self.assertIn(".english-object.selected>.transform-handle{pointer-events:all!important}", styles)
        self.assertIn("event.target.closest('[data-handle]')", app)
        self.assertIn("combined-selection", styles)
        importer = (ROOT / "illustrator/apply-chartlingo-result.jsx").read_text()
        self.assertIn("characterAttributes.strokeColor", importer)
        self.assertIn("characterAttributes.strokeWeight", importer)
        self.assertNotIn("pathItems.roundedRectangle", importer)

    def test_multi_selection_alignment_toolbar_and_direct_positioning(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        styles = (ROOT / "styles.css").read_text()
        self.assertIn('id="multiAlignTools"', index)
        for action in ["left", "top", "vcenter", "bottom", "right"]:
            self.assertIn(f'data-align-action="{action}"', index)
        self.assertEqual(index.count('class="align-guide"'), 6)
        self.assertIn(".alignment-toolbar button svg", styles)
        for action in ["hcenter", "distribute-h", "distribute-v"]:
            self.assertNotIn(f'data-align-action="{action}"', index)
        self.assertNotIn("Position and text box", index)
        self.assertIn("function alignSelection", app)
        self.assertIn("visibleBounds=new Map(selected.map(item=>[item.frameId,visualTextBounds(item)]))", app)
        self.assertIn("item.layout.x+=visibleLeft-visibleBounds.get(item.frameId).x", app)
        self.assertIn("if(selected.length===1){const item=selected[0],visible=visibleBounds.get(item.frameId);item.layout.x+=spec.width/2", app)
        self.assertIn("const visibleCenter=(visibleLeft+visibleRight)/2", app)
        self.assertIn("function updateAlignmentToolbar", app)
        self.assertIn("count<1", app)
        self.assertIn("alignSelection(button.dataset.alignAction)", app)
        self.assertIn("button.setAttribute('aria-pressed','true')", app)
        self.assertIn(".multi-align-tools[hidden]", styles)
        self.assertIn(".alignment-toolbar button:disabled", styles)

    def test_mismatch_checklist_requires_explicit_selection_and_structural_confirmation(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        styles = (ROOT / "styles.css").read_text()
        self.assertIn('id="mismatchSelectAll"', index)
        self.assertNotIn('id="mismatchDeselectAll"', index)
        self.assertNotIn('id="mismatchSelectFixable"', index)
        self.assertNotIn("Review mismatch groups", index)
        self.assertNotIn("Nothing is selected automatically", index)
        self.assertIn('id="mismatchSelectionCount"', index)
        self.assertIn('id="structuralMismatchConfirm"', index)
        self.assertIn('id="ignoreMismatch"', index)
        self.assertIn("checklist?'Ignore selected':'Ignore warning'", app)
        self.assertNotIn("available?'checked':'disabled'", app)
        self.assertIn("function updateMismatchSelectionUi", app)
        self.assertIn("`${count} of ${total} selected`", app)
        self.assertIn("$('confirmSeparation').disabled=!count", app)
        self.assertIn("$('ignoreMismatch').disabled=!count", app)
        self.assertIn("function selectMismatchRows", app)
        self.assertIn("event.target.checked", app)
        self.assertIn("checkbox.checked=true", app)
        self.assertIn("row.dataset.selectedCsvField=pair?.id||''", app)
        self.assertIn("row.dataset.status=pair?.en?'ready-to-apply':'requires-review'", app)
        self.assertNotIn("Suggested automatically", app)
        self.assertNotIn("Approved translation<select", app)
        self.assertIn("mismatch-row-select\">Translation<select", app)
        self.assertNotIn("<span>${index+1}</span>", app)
        self.assertIn("function ignoreSelectedMismatches", app)
        self.assertIn("function collectMismatchOperations", app)
        self.assertIn("function performMismatchChecklistApply", app)
        self.assertIn("row.dataset.resolution=resolution", app)
        self.assertIn("if(payload)performMismatchChecklistApply(payload)", app)
        self.assertIn("function mismatchChecklistEntries", app)
        self.assertIn("if(mismatchChecklistEntries().length)openMismatchChecklist();else closeMismatchPanel()", app)
        self.assertIn("const count=mismatchChecklistEntries().length", app)
        self.assertNotIn("state.pendingStructuralApply=payload", app)
        self.assertNotIn("structuralCount", app)
        self.assertIn("separationOperations", app)
        self.assertIn("event.target.closest('.format-choice')", app)
        self.assertIn("checkbox.checked=true;updateMismatchSelectionUi()", app)
        self.assertIn('data-resolution="keep"', app)
        self.assertIn('data-resolution="replace"', app)
        self.assertNotIn('Change text boxes to match CSV</button>', app)
        self.assertNotIn('Keep ChartLingo format</button>', app)
        self.assertIn('.format-choice.selected-decision', styles)
        self.assertNotIn('.fragmented-actions', styles)
        self.assertIn('#dataMismatchPanel .mismatch-header h2:before', styles)
        self.assertIn('border-color:#1672c4;background:#1672c4', styles)
        self.assertNotIn('.format-choice.selected-decision:after', styles)

    def test_identical_repeated_text_with_same_translation_is_not_a_mismatch(self):
        app = (ROOT / "app.js").read_text()
        self.assertIn("legitimateRepeat=matches.length>1", app)
        self.assertIn("CLV2.matchKey(object.originalSource?.sourceText||object.sourceText)===pairKey", app)
        self.assertIn("CLV2.normalize(object.english)===translation", app)
        self.assertIn("!reviewed&&!legitimateRepeat", app)

    def test_editor_preview_has_display_only_zoom_controls(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        styles = (ROOT / "styles.css").read_text()
        for control in ["previewZoomOut", "previewZoomPercent", "previewZoomIn", "previewZoomFit"]:
            self.assertIn(f'id="{control}"', index)
        self.assertNotIn('id="previewZoomReset"', index)
        self.assertIn("previewZoomMode:'fit'", app)
        self.assertIn("Math.max(.1,Math.min(4", app)
        self.assertIn("function applyEditorZoom", app)
        self.assertIn("function fitPreview", app)
        self.assertIn("state.previewZoomMode='locked-fit'", app)
        self.assertIn("['fit','locked-fit'].includes(state.previewZoomMode)", app)
        self.assertIn("event.ctrlKey||event.metaKey", app)
        self.assertIn("event.key==='0'", app)
        self.assertIn("event.key==='1'", app)
        self.assertIn(".preview-zoom-stage", styles)
        self.assertIn("overflow:auto", styles)

    def test_structured_table_layout_supports_wide_tables_and_multirow_headers(self):
        app = (ROOT / "app.js").read_text()
        self.assertIn("if(columns.length<2||rows.length<2)continue", app)
        self.assertNotIn("if(columns.length!==3||rows.length<2)continue", app)
        self.assertIn("if(columns.length>3)", app)
        self.assertIn("firstDataIndex=rows.findIndex", app)
        self.assertIn("isNumericContent(item.originalSource.sourceText)", app)
        self.assertIn("rows.slice(0,headerRowCount)", app)

    def test_numeric_y_axis_is_split_and_missing_footer_is_added(self):
        core = (ROOT / "core.js").read_text()
        app = (ROOT / "app.js").read_text()
        index = (ROOT / "index.html").read_text()
        self.assertIn("CLV2.splitNumericAxes=frames=>", core)
        self.assertIn("kind:'axis-tick'", core)
        self.assertIn("axisTickIndex:index", core)
        self.assertIn("CLV2.splitNumericAxes(CLV2.coalesceNumericAxes", core)
        self.assertIn("function ensureDefaultFooter", app)
        self.assertIn("LHZB Graphic: AI-Assisted Translation", app)
        self.assertIn("ensureDefaultFooter(artboard,list,spec)", app)
        self.assertIn("(?:zaobao|lhzb)", app)
        self.assertIn('core.js?v=20260922-02', index)
        self.assertIn('app.js?v=20260924-31', index)

    def test_ai_disclaimer_can_be_added_from_output_toolbar(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        self.assertIn('id="addAiDisclaimer"', index)
        self.assertIn('id="outputDimensions" hidden', index)
        self.assertIn("const AI_DISCLAIMER='LHZB Graphic: AI-Assisted Translation'", app)
        self.assertIn("function hasAiDisclaimer", app)
        self.assertIn("function toggleAiDisclaimer", app)
        self.assertIn("ensureDefaultFooter(artboard,list,outputSpec(artboard),true)", app)
        self.assertIn("sourceFooter?.layout?.fontSize||sourceFooter?.source?.style?.fontSize", app)
        self.assertIn("fontSize:fontSize/spec.scaleY", app)
        self.assertIn("generatedFooter:true,manualDisclaimer:force,dataMismatchStatus:'resolved'", app)
        self.assertIn("!object.generatedFooter&&!object.manualDisclaimer", app)
        self.assertIn("$('addAiDisclaimer').onclick=toggleAiDisclaimer", app)
        self.assertIn("'Remove AI disclaimer':'Add AI disclaimer'", app)
        self.assertIn("#addAiDisclaimer{display:none}#app.editing-mode #addAiDisclaimer{display:inline-flex}", (ROOT / "styles.css").read_text())

    def test_chart_typography_uses_local_noto_with_explicit_roboto_fallback(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        core = (ROOT / "core.js").read_text()
        styles = (ROOT / "styles.css").read_text()
        exporter = (ROOT / "illustrator/export-to-chartlingo.jsx").read_text()
        self.assertIn("primary:'Noto Sans SC',fallback:'Roboto'", core)
        self.assertIn("document.fonts.check('400 16px \"Noto Sans SC\"')", app)
        self.assertIn("state.resolvedFontFamily=notoAvailable?'Noto Sans SC':'Roboto'", app)
        self.assertIn("fontFallbackWarning", index)
        self.assertIn('<option value="Roboto">Roboto</option>', index)
        for weight in range(100, 1000, 100):
            self.assertIn(f'<option value="{weight}">', index)
        self.assertIn('font-family="${CLV2.escape(family)}"', app)
        self.assertIn('font-weight="${weight}"', app)
        self.assertIn('font-style="${fontStyle}"', app)
        self.assertIn("function explicitIllustratorTextFonts", app)
        self.assertIn("function illustratorNotoFace", app)
        self.assertIn("NotoSansSC-Regular", app)
        self.assertIn("NotoSansSC-Bold", app)
        self.assertIn("data-chartlingo-font-face", app)
        self.assertIn("node.removeAttribute('font-variation-settings')", app)
        self.assertIn("node.style.setProperty('font-weight',String(weight))", app)
        self.assertIn("function svgFontAttributes", app)
        self.assertIn("function validateSvgFontOutput", app)
        self.assertIn("validateSvgFontOutput(svg);validateSvgTextObjects", app)
        self.assertNotIn("async function fontData", app)
        self.assertNotIn("@font-face{font-family:Roboto", app)
        self.assertIn("fontWeight = numericFontWeight(fontStyleName)", exporter)
        self.assertIn("if (/thin/.test(value)) return 100", exporter)
        self.assertIn("if (/semibold|demibold/.test(value)) return 600", exporter)
        self.assertIn("if (/black/.test(value)) return 900", exporter)
        self.assertNotIn("Arial", app + core + styles + exporter)
        self.assertNotIn("sans-serif", app + core + styles + exporter)
        self.assertIn(":root{font-family:Roboto;", styles)

    def test_compact_highlight_and_automatic_outside_outline_controls(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        styles = (ROOT / "styles.css").read_text()
        self.assertNotIn("Text outline enabled", index)
        self.assertIn('id="partialHighlightTitle" hidden', index)
        self.assertIn('<option value="outside">Outside</option><option value="center">Center</option>', index)
        self.assertIn("alignment:'outside'", app)
        self.assertIn("item.stroke.enabled=enabled", app)
        self.assertIn(".highlight-rows{grid-template-columns:minmax(0,1fr) minmax(0,1fr)", styles)

    def test_exporter_has_simple_artboard_selection_and_optimized_photo_mode(self):
        exporter = (ROOT / "illustrator/export-to-chartlingo.jsx").read_text()
        app = (ROOT / "app.js").read_text()
        index = (ROOT / "index.html").read_text()
        self.assertIn("['Single artboard', 'Multiple artboards']", exporter)
        self.assertIn("{multiselect: true}", exporter)
        self.assertIn("Select at least one artboard from the list.", exporter)
        self.assertNotIn("Specific range in one package", exporter)
        self.assertNotIn("Each artboard as a separate package", exporter)
        self.assertIn("['Editable vectors + embedded photo (recommended)', 'High quality']", exporter)
        self.assertIn("imageMode: imageMode.selection.index === 0 ? 'optimized' : 'high-quality'", exporter)
        self.assertIn("if (exportChoice.imageMode === 'high-quality')", exporter)
        self.assertIn("artboards[i].previewSvg = null", exporter)
        self.assertIn("exportChoice.indices.length > 1 ? ' · '", exporter)
        self.assertIn("exportChoice.imageMode === 'optimized' ? artboards.length : artboards.length * 2", exporter)
        self.assertIn("version: '0.8.7'", exporter)
        self.assertIn("options.preserveEditability = false", exporter)
        self.assertIn("options.optimizeForSVGViewer = true", exporter)
        self.assertNotIn("function readScreenArtworkWithoutLiveText", exporter)
        self.assertNotIn("new ExportOptionsJPEG()", exporter)
        self.assertIn("artboards[i].artworkSvg = readArtworkWithoutLiveText", exporter)
        self.assertIn("Vector artwork was not flattened", exporter)
        self.assertIn("vectorsPreserved: true", exporter)
        self.assertNotIn("data-chartlingo-flattened-artwork", exporter)
        self.assertIn("data-chartlingo-flattened-artwork", app)
        self.assertIn("verifiedFile.length < payload.length", exporter)
        self.assertNotIn("savedText = verifiedFile.read()", exporter)
        self.assertIn("const artwork=board.artworkSvg", app)
        self.assertIn("background}${texts}", app)
        self.assertIn('app.js?v=20260924-31', index)

    def test_editor_can_add_a_manual_editable_text_box(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        styles = (ROOT / "styles.css").read_text()
        self.assertIn('id="addText"', index)
        self.assertIn("function addManualText", app)
        self.assertIn("method:'manually added'", app)
        self.assertIn("manuallyAdded:true", app)
        self.assertIn("state.manualSelection=new Set([id])", app)
        self.assertIn("$('editText')?.select()", app)
        self.assertIn(".add-text-button", styles)

    def test_multi_selection_moves_as_a_group_and_supports_keyboard_nudging(self):
        app = (ROOT / "app.js").read_text()
        styles = (ROOT / "styles.css").read_text()
        self.assertIn('data-group-selection="true"', app)
        self.assertIn("function selectedBounds", app)
        self.assertIn("function constrainedSelectionDelta", app)
        self.assertIn("const visible=list.map(visualTextBounds)", app)
        self.assertIn("function moveSelectedBy", app)
        self.assertIn("selected.some(item=>item.originalSource?.role==='TITLE'||item.source?.role==='TITLE')", app)
        self.assertIn("function bindGroupMovement", app)
        self.assertIn("origin.x+last.dx", app)
        self.assertIn("origin.y+last.dy", app)
        self.assertIn("spec.width-bounds.right", app)
        self.assertIn("spec.cropTop+spec.height-bounds.bottom", app)
        self.assertIn("ArrowLeft", app)
        self.assertIn("event.shiftKey?10:1", app)
        self.assertIn("state.manualSelection.clear()", app)
        self.assertIn("pointer-events:all;cursor:move", styles)

    def test_removed_preflight_ui_and_invalid_svg_control_characters(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        styles = (ROOT / "styles.css").read_text()
        self.assertNotIn(">Run checks<", index)
        self.assertNotIn("issues-panel", index)
        self.assertNotIn("<h2>Exceptions</h2>", index)
        self.assertIn('id="statusSummary" hidden', index)
        self.assertIn('id="issues" hidden', index)
        self.assertIn("\\u0000-\\u0008", app)
        self.assertIn("documentNode.querySelector('parsererror')", app)
        self.assertIn(".lower-grid{grid-template-columns:minmax(0,1fr)}", styles)

    def test_editor_can_toggle_chinese_reference_without_scope_or_reset_ui(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        styles = (ROOT / "styles.css").read_text()
        self.assertNotIn("<summary>Edit scope</summary>", index)
        self.assertNotIn(">Selected text only<", index)
        self.assertNotIn(">Reset generated<", index)
        self.assertNotIn(">Reset style<", index)
        self.assertNotIn(">Cancel<", index)
        self.assertIn('id="toggleReference"', index)
        self.assertIn('id="editorReferencePanel"', index)
        self.assertIn('id="editorSourceCanvas"', index)
        self.assertIn("showReference:false", app)
        self.assertIn("state.showReference=!state.showReference", app)
        self.assertIn("state.showReference?'Hide Chinese reference':'Show Chinese reference'", app)
        self.assertIn("show-reference .editing-studio", styles)
        self.assertIn("show-reference .editor-reference-panel", styles)

    def test_editor_has_save_back_tab_without_duplicate_back_or_apply_buttons(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        styles = (ROOT / "styles.css").read_text()
        self.assertIn("function renderTabs(){const host=$('artboardTabs');host.innerHTML='';host.hidden=true}", app)
        self.assertIn('id="saveBackToGallery"', index)
        self.assertIn('class="editor-toolbar-secondary"', index)
        self.assertIn("$('saveBackToGallery').onclick=exitEditor", app)
        self.assertIn("renderTabs();renderCanvases();renderInspector()", app)
        self.assertNotIn('id="exitEditor"', index)
        self.assertNotIn('id="applyInspector"', index)
        self.assertIn('class="lower-grid" hidden', index)
        self.assertIn(".lower-grid[hidden]{display:none!important}", styles)
        self.assertNotIn("#applyInspector", styles)

    def test_top_toolbar_groups_import_generate_and_export_dropdown(self):
        index = (ROOT / "index.html").read_text()
        app = (ROOT / "app.js").read_text()
        styles = (ROOT / "styles.css").read_text()
        top_actions = index[index.index('<div class="top-actions">'):index.index('</div>\n  </header>')]
        self.assertIn('id="packageInput"', top_actions)
        self.assertIn('id="csvInput"', top_actions)
        self.assertNotIn('id="generate"', top_actions)
        self.assertIn('Import .chartlingo File', top_actions)
        self.assertIn('Import CSV or TXT', top_actions)
        self.assertIn('class="toolbar-divider"', top_actions)
        self.assertIn('class="export-menu"', top_actions)
        self.assertIn('id="exportSvg"', top_actions)
        self.assertIn('id="exportPng"', top_actions)
        self.assertNotIn('id="exportResult"', top_actions)
        self.assertIn(".export-menu-popover", styles)
        self.assertIn(".export-option", styles)
        self.assertIn("removeAttribute('open')", app)
        self.assertIn('class="projectbar" hidden', index)
        self.assertIn(".projectbar[hidden]{display:none!important}", styles)
        self.assertIn("#app:not(.editing-mode) .canvas-host svg{width:auto;max-width:100%;height:auto;max-height:70vh}", styles)

    def test_generation_starts_automatically_after_both_inputs_are_ready(self):
        app = (ROOT / "app.js").read_text()
        index = (ROOT / "index.html").read_text()
        self.assertIn("async function maybeAutoGenerate()", app)
        self.assertIn("await maybeAutoGenerate()", app)
        self.assertGreaterEqual(app.count("await maybeAutoGenerate()"), 2)
        self.assertIn("generationInProgress", app)
        self.assertNotIn("$('generate')", app)
        self.assertIn('app.js?v=20260924-31', index)

    def test_illustrator_tab_tables_export_as_independent_cells(self):
        exporter = (ROOT / "illustrator/export-to-chartlingo.jsx").read_text()
        importer = (ROOT / "illustrator/apply-chartlingo-result.jsx").read_text()
        self.assertIn("function tableRows", exporter)
        self.assertIn("numbered.numberedList = true", exporter)
        self.assertIn("plain.length >= 3", exporter)
        self.assertIn("plain.plainList = true", exporter)
        self.assertIn("function pairedAxisLabels", exporter)
        self.assertIn("result.push({year: first[i], period: second[i]})", exporter)
        self.assertIn("kind: 'axis-year'", exporter)
        self.assertIn("kind: 'axis-period'", exporter)
        self.assertIn("'-x' + (columnIndex + 1) + '-year'", exporter)
        self.assertIn("'-x' + (columnIndex + 1) + '-period'", exporter)
        self.assertIn("groupId: groupId", exporter)
        self.assertIn("fieldType: 'year'", exporter)
        self.assertIn("axisField: 'year'", exporter)
        self.assertIn("axisField: fieldType", exporter)
        self.assertIn("function creditLines", exporter)
        self.assertIn("kind: 'credit-line'", exporter)
        self.assertIn("itemId = baseId + '-' + fieldType", exporter)
        self.assertIn("fieldType: fieldType", exporter)
        self.assertIn("-x\\d+-(?:year|period)", importer)
        self.assertIn("rows.plainList ? 'list-item' : 'table-cell'", exporter)
        self.assertIn("rows.numberedList", exporter)
        self.assertIn("width * 0.28", exporter)
        self.assertIn("function tableColumns", exporter)
        self.assertIn("x: anchors[i]", exporter)
        self.assertNotIn("(anchors[i - 1] + anchors[i]) / 2", exporter)
        self.assertIn("'-r' + (rowIndex + 1) + '-c' + (columnIndex + 1)", exporter)
        self.assertIn("'list-item' : 'table-cell'", exporter)
        self.assertIn("candidate.kind === 'list-item'", exporter)
        self.assertIn("virtualCell: true", exporter)
        self.assertIn("sourceFrameId(sourceId)", importer)

    def test_legacy_packages_warn_instead_of_failing(self):
        core = (ROOT / "core.js").read_text()
        app = (ROOT / "app.js").read_text()
        self.assertIn("copy.legacyExporter=", core)
        self.assertIn("CLV2.removeLegacyOutlinedText", core)
        self.assertIn("fill===target.color", core)
        self.assertIn("CLV2.removeLegacyOutlinedText(packaged||sourceSvg(board),board.textFrames)", app)
        self.assertIn("Older package imported", app)
        self.assertIn("LEGACY_EXPORTER", app)
        self.assertNotIn("This package was made by an older Illustrator exporter", core)

    def test_original_application_paths_are_not_referenced_for_writes(self):
        for path in ROOT.rglob("*"):
            if path.is_file() and path.suffix in {".js", ".jsx", ".html"}:
                text = path.read_text(errors="ignore")
                self.assertNotIn("../src/", text)
                self.assertNotIn("../index.html", text)


if __name__ == "__main__":
    unittest.main()
