const $=id=>document.getElementById(id);
const state={pkg:null,pairs:[],active:0,objects:new Map(),issues:[],selected:null};
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),2600)}
function board(){return state.pkg?.document.artboards[state.active]}
function objects(){return state.objects.get(board()?.id)||[]}
function outputSpec(artboard){const width=1200,scale=width/artboard.bounds.width,height=Math.round(artboard.bounds.height*scale);return {width,height,scale,scaleX:scale,scaleY:scale}}
function outputFrames(artboard){const spec=outputSpec(artboard),frames=artboard.textFrames.map(frame=>{const x=frame.bounds.x*spec.scale,y=frame.bounds.y*spec.scale,width=Math.max(frame.bounds.width*spec.scale,24),height=Math.max(frame.bounds.height*spec.scale,1),style={...frame.style,fontSize:(frame.style.fontSize||14)*spec.scale};return {...frame,style,bounds:{x,y,width,height},originalBounds:frame.bounds,permittedRegion:frame.permittedRegion?{x:frame.permittedRegion.x*spec.scale,y:frame.permittedRegion.y*spec.scale,width:frame.permittedRegion.width*spec.scale,height:frame.permittedRegion.height*spec.scale}:null}});for(const frame of frames){const center=frame.bounds.x+frame.bounds.width/2,verticalCenter=frame.bounds.y+frame.bounds.height/2,sameRow=frames.filter(other=>other!==frame&&Math.abs((other.bounds.y+other.bounds.height/2)-verticalCenter)<=Math.max(frame.bounds.height,other.bounds.height,frame.style.fontSize||14)*.7).sort((a,b)=>a.bounds.x-b.bounds.x),left=sameRow.filter(other=>other.bounds.x+other.bounds.width/2<center).at(-1),right=sameRow.find(other=>other.bounds.x+other.bounds.width/2>center),regionLeft=left?((left.bounds.x+left.bounds.width/2)+center)/2:Math.max(0,frame.bounds.x-12),regionRight=right?(center+(right.bounds.x+right.bounds.width/2))/2:Math.min(spec.width,Math.max(frame.bounds.x+frame.bounds.width+24,spec.width-12));frame.permittedRegion={x:regionLeft+6,y:Math.max(0,frame.bounds.y-(frame.style.fontSize||14)*.35),width:Math.max(20,regionRight-regionLeft-12),height:Math.max(frame.bounds.height,frame.permittedRegion?.height||frame.bounds.height)}}return frames}
async function ensureRoboto(){if(document.fonts?.load){await Promise.all([document.fonts.load('400 16px Roboto'),document.fonts.load('700 16px Roboto')]);await document.fonts.ready}}
function download(name,blob){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
function readFile(file,mode='text'){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(reader.error);reader.onload=()=>resolve(reader.result);mode==='arrayBuffer'?reader.readAsArrayBuffer(file):reader.readAsText(file)})}
function importPackage(raw){state.pkg=CLV2.validatePackage(typeof raw==='string'?JSON.parse(raw):raw);state.active=0;state.objects.clear();state.issues=[];$('emptyState').hidden=true;$('app').hidden=false;render();toast(`Imported ${state.pkg.document.artboards.length} artboard${state.pkg.document.artboards.length===1?'':'s'}.`)}
function sourceSvg(board){if(board.previewSvg)return board.previewSvg;if(state.pkg.document.artboards.length===1&&state.pkg.document.previewSvg)return state.pkg.document.previewSvg;const texts=board.textFrames.map(t=>`<text x="${t.bounds.x}" y="${t.bounds.y+(t.style.fontSize||14)}" font-family="${CLV2.escape(t.style.fontFamily)}" font-size="${t.style.fontSize||14}" fill="${t.style.fill||'#111'}">${CLV2.escape(t.sourceText)}</text>`).join('');return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${board.bounds.width} ${board.bounds.height}"><rect width="100%" height="100%" fill="white"/>${texts}</svg>`}
function artworkSvg(board){if(board.artworkSvg)return board.artworkSvg;if(state.pkg.document.artboards.length===1&&state.pkg.document.artworkSvg)return state.pkg.document.artworkSvg;return CLV2.removeSourceText(sourceSvg(board))}
function svgBody(source){const parsed=new DOMParser().parseFromString(source,'image/svg+xml');return parsed.documentElement.innerHTML}
function englishSvg(board,forExport=false){const spec=outputSpec(board),source=svgBody(artworkSvg(board)),rendered=objects().filter(o=>o.english&&o.layout).map(o=>{const l=o.layout,s=o.source.style,anchor=s.alignment==='center'?l.x+l.width/2:s.alignment==='right'?l.x+l.width:l.x,textAnchor=s.alignment==='center'?'middle':s.alignment==='right'?'end':'start',selected=!forExport&&state.selected===o.frameId?'<rect x="'+(l.x-4)+'" y="'+(l.y-4)+'" width="'+(l.width+8)+'" height="'+(l.height+8)+'"/>':'';return `<g class="english-object${state.selected===o.frameId?' selected':''}" data-id="${o.frameId}">${selected}<text x="${anchor}" y="${l.y+l.fontSize}" text-anchor="${textAnchor}" font-family="Roboto,Arial,sans-serif" font-size="${l.fontSize}" fill="${s.fill||'#111'}">${l.lines.map((line,i)=>`<tspan x="${anchor}" dy="${i?l.lineHeight:0}">${CLV2.escape(line)}</tspan>`).join('')}</text></g>`}).join('');return `<svg xmlns="http://www.w3.org/2000/svg" width="${spec.width}" height="${spec.height}" viewBox="0 0 ${spec.width} ${spec.height}"><g id="source-artwork" transform="scale(${spec.scale})">${source}</g><g id="english-layer">${rendered}</g></svg>`}
async function generate(){await ensureRoboto();for(const artboard of state.pkg.document.artboards){const mappings=CLV2.match(artboard.textFrames,state.pairs),spec=outputSpec(artboard),prepared=outputFrames(artboard),list=mappings.map(mapping=>{const original=artboard.textFrames.find(t=>t.id===mapping.frameId),source=prepared.find(t=>t.id===mapping.frameId),lines=mapping.sourceRetained&&original.visibleLines?.length>1?original.visibleLines:null;return {...mapping,source,originalSource:original,layout:CLV2.fit(source,mapping.english,spec,{sourceRetained:mapping.sourceRetained,lines})}});state.objects.set(artboard.id,list)}runChecks();render();toast('English layer generated in Roboto at the original text positions.')}
function runChecks(){state.issues=[];for(const artboard of state.pkg.document.artboards){const list=state.objects.get(artboard.id)||artboard.textFrames.map(source=>({frameId:source.id,source,english:'',layout:null}));for(const issue of CLV2.validate(artboard.bounds,list))state.issues.push({...issue,artboardId:artboard.id,artboardName:artboard.name})}renderIssues();return state.issues}
function updateEnglish(frameId,value){const object=objects().find(o=>o.frameId===frameId);if(!object)return;object.english=value;object.layout=value?CLV2.fit(object.source,value,board().bounds):null;runChecks();renderCanvases();renderMappings();renderSummary()}
function renderTabs(){const host=$('artboardTabs');host.innerHTML='';state.pkg.document.artboards.forEach((item,index)=>{const button=document.createElement('button');button.textContent=item.name||`Artboard ${index+1}`;button.setAttribute('aria-current',index===state.active);button.onclick=()=>{state.active=index;state.selected=null;render()};host.append(button)})}
function renderCanvases(){const b=board(),spec=outputSpec(b);$('sourceDimensions').textContent=`${b.bounds.width} × ${b.bounds.height}`;$('outputDimensions').textContent=`${spec.width} × ${spec.height}`;$('sourceCanvas').innerHTML=sourceSvg(b);$('outputCanvas').innerHTML=englishSvg(b);$('outputCanvas').querySelectorAll('[data-id]').forEach(node=>node.onclick=()=>{state.selected=node.dataset.id;renderCanvases();renderMappings()})}
function renderMappings(){const host=$('mappingTable'),list=objects();host.innerHTML='';for(const frame of board().textFrames){const object=list.find(o=>o.frameId===frame.id),row=document.createElement('div');row.className='mapping-row';const confidence=object?(object.confidence>=.8?'good':object.confidence?'review':'missing'):'missing';row.dataset.frameId=frame.id;row.innerHTML=`<div class="source">${CLV2.escape(frame.sourceText)}<small>${CLV2.escape(frame.name||frame.id)} · ${frame.kind||'text'} · ${frame.visibleLines?.length||1} visible line${frame.visibleLines?.length===1?'':'s'}</small></div><textarea aria-label="English for ${CLV2.escape(frame.name||frame.id)}" ${object?'':'disabled'}>${CLV2.escape(object?.english||'')}</textarea><div class="confidence ${confidence}">${object?`${Math.round(object.confidence*100)}%<small>${object.method}</small>`:'Not generated'}</div>`;const textarea=row.querySelector('textarea');textarea.onchange=()=>updateEnglish(frame.id,textarea.value);row.onclick=e=>{if(e.target!==textarea){state.selected=frame.id;renderCanvases()}};host.append(row)}const mapped=list.filter(o=>o.english).length;$('coverage').textContent=`${mapped} of ${board().textFrames.length} mapped`}
function renderIssues(){const host=$('issues');host.innerHTML='';const active=state.issues.filter(i=>i.artboardId===board()?.id);if(!active.length){host.innerHTML='<div class="issue ok"><strong>Ready for review</strong>No blocking layout problems detected on this artboard.</div>';return}for(const issue of active){const div=document.createElement('div');div.className=`issue ${issue.severity}`;div.innerHTML=`<strong>${CLV2.escape(issue.rule)}</strong>${CLV2.escape(issue.message)}`;div.onclick=()=>{state.selected=issue.objectId;renderCanvases();document.querySelector(`[data-frame-id="${CSS.escape(issue.objectId)}"]`)?.scrollIntoView({behavior:'smooth',block:'center'})};host.append(div)}}
function renderSummary(){const total=state.pkg.document.artboards.reduce((n,a)=>n+a.textFrames.length,0),mapped=[...state.objects.values()].flat().filter(o=>o.english).length,retained=[...state.objects.values()].flat().filter(o=>o.sourceRetained).length,errors=state.issues.filter(i=>i.severity==='error').length;$('statusSummary').textContent=`${state.pkg.document.artboards.length} artboard${state.pkg.document.artboards.length===1?'':'s'} · ${mapped}/${total} shown · ${retained} source retained · ${errors} blocking issue${errors===1?'':'s'}`;$('generate').disabled=!state.pkg}
function render(){const b=board();$('projectName').textContent=state.pkg.document.name;renderTabs();renderCanvases();renderMappings();renderIssues();renderSummary()}
async function fontData(path){const response=await fetch(path),bytes=new Uint8Array(await response.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode.apply(null,bytes.subarray(i,i+8192));return `data:font/ttf;base64,${btoa(binary)}`}
async function exportSvg(){if(!objects().some(o=>o.english)){toast('Generate the English layer first.');return}await ensureRoboto();const regular=await fontData('fonts/Roboto-Regular.ttf'),bold=await fontData('fonts/Roboto-Bold.ttf'),style=`<style>@font-face{font-family:Roboto;src:url('${regular}') format('truetype');font-weight:400}@font-face{font-family:Roboto;src:url('${bold}') format('truetype');font-weight:700}</style>`,svg=englishSvg(board(),true).replace(/(<svg[^>]*>)/,`$1<defs>${style}</defs>`);download(`${board().name.replace(/\W+/g,'-')}_EN.svg`,new Blob([svg],{type:'image/svg+xml'}))}
async function exportPng(){if(!objects().some(o=>o.english)){toast('Generate the English layer first.');return}await ensureRoboto();const spec=outputSpec(board()),svg=englishSvg(board(),true),blob=new Blob([svg],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),image=new Image();image.onload=()=>{const canvas=document.createElement('canvas');canvas.width=spec.width;canvas.height=spec.height;canvas.getContext('2d').drawImage(image,0,0);URL.revokeObjectURL(url);canvas.toBlob(png=>download(`${board().name.replace(/\W+/g,'-')}_EN.png`,png),'image/png')};image.onerror=()=>toast('PNG rendering failed. Try SVG export.');image.src=url}
function exportResult(){runChecks();const result={schema:'https://chartlingo.local/schemas/result-v2.json',schemaVersion:'2.0.0',sourceDocument:{id:state.pkg.document.id,revision:state.pkg.document.revision,name:state.pkg.document.name},generatedAt:new Date().toISOString(),artboards:state.pkg.document.artboards.map(artboard=>{const spec=outputSpec(artboard);return {id:artboard.id,name:artboard.name,outputCanvas:spec,textFrames:(state.objects.get(artboard.id)||[]).filter(o=>o.english).map(o=>({id:o.frameId,english:o.english,sourceText:o.originalSource.sourceText,sourceRetained:o.sourceRetained,layout:o.layout,style:{fontFamily:'Roboto',fontPostScriptName:'Roboto-Regular',fontSize:o.layout.fontSize,alignment:o.source.style.alignment,fill:o.source.style.fill}}))}}),validation:{issues:state.issues}};download(`${state.pkg.document.name.replace(/\W+/g,'-')}.chartlingo-result`,new Blob([JSON.stringify(result,null,2)],{type:'application/json'}))}
$('packageInput').onchange=async e=>{try{if(e.target.files[0])importPackage(await readFile(e.target.files[0]))}catch(error){toast(error.message)}finally{e.target.value=''}};
$('csvInput').onchange=async e=>{try{if(!e.target.files[0])return;state.pairs=CLV2.parseCsv(await readFile(e.target.files[0]));toast(`Imported ${state.pairs.length} approved translation${state.pairs.length===1?'':'s'}.`);renderSummary()}catch(error){toast(error.message)}finally{e.target.value=''}};
$('loadSample').onclick=()=>{importPackage(CLV2.sample());state.pairs=[{id:'headline-01',ch:'航程缩短3小时，新加坡经济可获什么？',en:'What can Singapore gain from a three-hour reduction in flight time?'},{id:'subtitle-01',ch:'航空与旅游业的潜在收益',en:'Potential benefits for aviation and tourism'},{id:'source-01',ch:'资料来源：示例数据',en:'Source: sample data'}];generate()};
$('generate').onclick=generate;$('validate').onclick=()=>{runChecks();renderSummary();toast(state.issues.length?`Found ${state.issues.length} issue${state.issues.length===1?'':'s'}.`:'No layout issues found.')};$('exportSvg').onclick=exportSvg;$('exportPng').onclick=exportPng;$('exportResult').onclick=exportResult;
